-- liquibase formatted sql

-- changeset kirill:1
CREATE TABLE IF NOT EXISTS users
(
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username   VARCHAR(255) NOT NULL UNIQUE,
    password   VARCHAR(255) NOT NULL,
    first_name VARCHAR(255) NOT NULL,
    last_name  VARCHAR(255) NOT NULL,
    phone      VARCHAR(255) NOT NULL,
    role       VARCHAR(20)  NOT NULL,
    image      VARCHAR(255)
);

-- changeset kirill:2
CREATE TABLE IF NOT EXISTS ads
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title       VARCHAR(255) NOT NULL,
    price       INTEGER      NOT NULL,
    description TEXT,
    author_id   INTEGER      NOT NULL REFERENCES users (id),
    image       VARCHAR(255),
    created_at  BIGINT
);

-- changeset kirill:3
CREATE TABLE IF NOT EXISTS comments
(
    id        INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text      TEXT     NOT NULL,
    author_id INTEGER NOT NULL REFERENCES users (id),
    ad_id     INTEGER NOT NULL REFERENCES ads (id),
    created_at BIGINT
);
